### ISSUE TITLE
Brainf#ck not working properly. How to uninstall/repair?

### ISSUE THREAD

**Issue by Pdune** [aztecrabbit/brainfuck-psiphon-pro-go#10]
Was  installing brainf#ck and it successfully installed- ![IMG-20200718-WA0118.jpg](https://user-images.githubusercontent.com/68368008/87855537-51164200-c919-11ea-9263-abd370382163.jpg)

But when i reopened it, this would show![IMG-20200718-WA0173.jpg](https://user-images.githubusercontent.com/68368008/87855546-68552f80-c919-11ea-83de-5f29dadad544.jpg)

How can i uninstall it so i can install properly?

**Comment by aztecrabbit** [comment]
Config in config.json file are incorrect. Remove that file, and run `brainfuck-psiphon-pro-go` again

**Comment by Pdune** [comment]
Okay so I've just removed the file and I'm running the brainfuck-psiphon-pro-go again...but I cannot configure the config.json properly. How can I make it correct?

**Comment by aztecrabbit** [comment]
https://www.digitalocean.com/community/tutorials/an-introduction-to-json

Use tab, not space.
