### ISSUE TITLE
Tidak mau konek

### ISSUE THREAD

**Issue by statting** [aztecrabbit/brainfuck-psiphon-pro-go#11]
klo saya konek menggunakan kartu trik ( Telkomsel Gamemax , indosat ilped dll.) proxy socks g jalan

klo saya konek menggunakan kuota reguler proxy socks nya jalan

--------------------------------------------------------------------------------

if I connect using a trick simcard (Telkomsel Gamemax , indosat ilped etc.) Proxy socks won't work

if I connect using the regular quota proxy socks work

**Comment by aztecrabbit** [comment]
Ada bacaan connected warna kuning ga? Kalau ada, seharusnya si bisa
