### ISSUE TITLE
Socks5 No Root  Android (TERMUX) No Resolv

### ISSUE THREAD

**Issue by alsiber** [aztecrabbit/brainfuck-psiphon-pro-go#2]
SocksDroid -> 127.0.0.1:3080 (Exclude com.termux) = Ga bisa resolv google
Tun2Tap -> 127.0.0.1:3080 (Exclude Termux) = Sama ga bisa resolv 
mohon bantuannya pak

**Comment by aztecrabbit** [comment]
DNSnya gausah diaktifin, app diatas bisa dipake ko disini, atau pake app sejenis, cari di playstore, [Postern](https://play.google.com/store/apps/details?id=com.tunnelworkshop.postern) misalnya, dll. Atau kalo masih stuck, root hpnya, pake [ProxyDroid](https://play.google.com/store/apps/details?id=org.proxydroid), atau pake [Domain Fronting](https://github.com/aztecrabbit/Domain-Fronting) kalo gamau root. Kesalahannya bukan di brainfuck, jadi di close.
