### ISSUE TITLE
HTTP HEADER on config.json

### ISSUE THREAD

**Issue by ingnelson** [aztecrabbit/brainfuck-psiphon-pro-go#3]
Can we create payload on "config.json" payload like http injector ? And not only add a host ? Maybe add HTTP HEADERS ?
Thanks.

**Comment by aztecrabbit** [comment]
Use `Inject -> Type -> 0`, if `Inject -> Rules` is `"*:*" ["*"]` that will using direct method, if `Inject -> Rules` is `"*:*": ["proxy.example.com:8080"]` that will using http proxy. Change payload in `config.json`, `Inject -> Payload` to like in Http Injector. And change `Psiphon -> Protocols` to `SSH` nor `OSSH`. I suggest using another tool to run a tunnel that uses payload, like [Brainfuck Tunnel Go](https://github.com/aztecrabbit/brainfuck-tunnel-go) or [Brainfuck Tunnel Openvpn](https://github.com/aztecrabbit/brainfuck-tunnel-openvpn).
