### ISSUE TITLE
Can brainfuck work with other ISP providers ?

### ISSUE THREAD

**Issue by ingnelson** [aztecrabbit/brainfuck-psiphon-pro-go#4]
Can brainfuck work with other ISP providers ?

on config.json file i change the rule akamai.net with other domain but it does not connect .

Can you explain how to use this program with other providers ? Not only XL or Telkomsel.

Please.

**Comment by aztecrabbit** [comment]
Use [bugscanner](https://github.com/aztecrabbit/bugscanner) `--mode direct` to scan bug, that tool will generate the config automatically for brainfuck psiphon pro go

**Comment by sonvirgo** [comment]
> Use [bugscanner](https://github.com/aztecrabbit/bugscanner) `--mode direct` to scan bug, that tool will generate the config automatically for brainfuck psiphon pro go

In '--mode direct', my ISP only allow 'cross-CDN' traffic, specifically Akamai.net.
With such topology, the only working protocols are FRONTED-MEEK- , that requires at least 4 hosts, 2 of which belong to the ISP's CDN, (1) & (2) ,as seen on the below picture.
![image](https://user-images.githubusercontent.com/10823037/206937077-56dc0c93-6bc2-4572-a0c9-96afcd2476c9.png)
So how to use bugscanner --mode direct to detect bugs and to generate config file?
I have run  'bugscanner --mode direct' but nothing happened.
![image](https://user-images.githubusercontent.com/10823037/206937124-473003b4-5304-44d5-897f-f7906cd7c0b2.png)
Infact I have to inject scanning function into the psiphon-tunnel-core to find out the (1) bugs. But (2) bugs is another story, as it is a FQDN?
