### ISSUE TITLE
Payload libinject.go

### ISSUE THREAD

**Issue by ingnelson** [aztecrabbit/brainfuck-psiphon-pro-go#5]
Hello.
Can you explain where to save the libinject.go on Termux ? And how to excecute it with brainfuck , please ?

https://github.com/aztecrabbit/libinject/blob/66586ad1041b5c9f7e49161a6c71b11495bf24f6/libinject.go?fbclid=IwAR1QOfpQk-boZE9iioSjjVLzVW2nDchMnXJh81QcXN_sNIkU4FufJlg8k9k#L210-L222

**Comment by aztecrabbit** [comment]
libinject.go is library only, that lib is used by this app. You can change Inject Type to 0 and Inject Payload to like in any injector app (https://github.com/aztecrabbit/libinject/blob/66586ad1041b5c9f7e49161a6c71b11495bf24f6/libinject.go?fbclid=IwAR1QOfpQk-boZE9iioSjjVLzVW2nDchMnXJh81QcXN_sNIkU4FufJlg8k9k#L210-L222) if you want to use direct or http proxy method with payload.
