### ISSUE TITLE
Are support UPDGW port for online game?

### ISSUE THREAD

**Issue by khakimsetia** [aztecrabbit/brainfuck-psiphon-pro-go#6]
Please solve this.
Brainfuck psiphon work.
Tapi adakah cara lain untuk utk menyelesaikan permasalahan BADVPN Updgw yg tidak tersedia di server psiphon?

Tolong tambahkan port HTTP di project ini.
Sangat membantu

**Comment by aztecrabbit** [comment]
Badvpn Udpgw not support, try different tool. Port http for what?
