### ISSUE TITLE
Error Bug XL PUBG

### ISSUE THREAD

**Issue by the-wtj** [aztecrabbit/brainfuck-psiphon-pro-go#9]
I try bug pubg and this the output, maybe coid or error

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x5b52f49884]

goroutine 1 [running]:
main.main()
        /data/data/com.termux/files/home/go/src/github.com/aztecrabbit/brainfuck-psiphon-pro-go/main.go:101 +0x61c

**Comment by NightMareBosz** [comment]
udah solved blm? kalo blm hapus ajh brainfucknya, trus instal ulang .. #beres

**Comment by the-wtj** [comment]
Not yet

**Comment by aztecrabbit** [comment]
Config in config.json file are incorrect. Remove that file, and run `brainfuck-psiphon-pro-go` again
